### ISSUE TITLE
No such file or directory: 'playerdefault.json'

### ISSUE THREAD

**Issue by ihategravel2** [RavinMaddHatter/plot-world-maker-bedrock#6]
Upon Pushing "Make Pack" You get a error.

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1883, in __call__
  File "plotzMaker.py", line 17, in makepack
    with open("playerdefault.json") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'playerdefault.json'

**Comment by RavinMaddHatter** [comment]
Do you have the lookups adjacent to the program or just the exe. You need
the whole package the exe doesn't work stand alone

**Comment by ihategravel2** [comment]
I have the .exe with all the other files in the folder.

**Comment by ihategravel2** [comment]
I added the file itself from the repository and it worked. I'm not sure why it was just missing for some reason.
